import { createContext, useContext, useState, useEffect } from 'react';

const TRANSLATIONS = {
  es: {
    searchParams: "Filtros", searchString: "Búsqueda Libre", searchPlaceholder: "Ej: Proliferate, Dragon...",
    scopeName: "Nombre", scopeType: "Tipo", scopeText: "Texto",
    uiLang: "Texto Interfaz", imgLang: "Arte / Imagen", commander: "Puede ser Comandante",
    colorId: "Identidad de Color", mainType: "Tipo de Carta", rarity: "Rareza", format: "Formato Legal",
    creature: "Criatura", instant: "Instantáneo", sorcery: "Conjuro", artifact: "Artefacto",
    enchantment: "Encantamiento", planeswalker: "Planeswalker", anyFormat: "Todos",
    cmcMax: 'CMC Máx',
    commanderLegal: 'Debe ser legal como Comandante',
    imageLang: 'Idioma Arte / Imagen',
    setFilter: 'Edición (Set)',
    searchSet: 'Buscar edición...',
    allSets: 'Cualquier Edición',
    common: "Común", uncommon: "Infrecuente", rare: "Rara", mythic: "Mítica",
    invoke: "Invocar Carta", searchCards: "Buscar Cartas",
    welcomeTitle: "Bienvenido a SeaCards", welcomeDesc: 'Configura tus filtros en el panel lateral y presiona el botón para explorar el multiverso.',
    scrying: "Scrying el multiverso...", errorEmpty: "El multiverso está vacío. No se encontraron cartas con esta combinación de filtros.",
    otherVersions: "Estilos y Versiones Alternativas",
    savedCards: "CARTAS FAVORITAS",
    backToSeaCards: "Volver a SeaCards",
    fetchingSaved: "Invocando datos del multiverso...",
    noSavedCards: "Tu colección está vacía",
    noSavedDesc: "Vuelve a SeaCards e invoca algunas cartas para guardarlas aquí.",
    noMatchSaved: "Ninguna carta coincide con los filtros",
    noMatchDesc: "Prueba a limpiar los filtros en el panel lateral.",
    saveBtn: "Guardar en Favoritos",
    savingBtn: "Guardando...",
    savedAlert: "¡Guardada en Favoritos!",
    deleteBtn: "Eliminar",
    confirmDelete: "¿Seguro que quieres quitar esta carta de tus Favoritos?",
    searchTitle: "Búsqueda Avanzada",
    searchDesc: 'Configura tus filtros y presiona "Buscar Cartas" para ver todos los resultados posibles.',
    foundCards: "Se encontraron",
    cardsMax: "cartas (mostrando máximo 175)",
    invokeBtn: "Invocar",
    searchNav: "Buscar",
    savedNav: "Favoritos",
    logoutTitle: "Cerrar Sesión",
    loginTitle: "Identifícate para acceder al Multiverso",
    emailPlaceholder: "tu@email.com",
    passwordPlaceholder: "Tu contraseña",
    loginBtn: "Entrar al Multiverso",
    loggingIn: "Entrando...",
    noAccount: "¿Aún no tienes cuenta?",
    createAccount: "Regístrate aquí",
    hasAccount: "¿Ya tienes las llaves?",
    loginHere: "Entra aquí",
    marketUsd: "Mercado (USD)",
    marketEur: "Mercado (EUR)",
    set: "Set",
    noImage: "Sin imagen disponible",
    manaCmc: "Maná (CMC)",
    min: "Min",
    max: "Max",
    reset: "Reset",
    processing: "Procesando...",
    view: "Ver",
    bannedIn: "Baneada en",
    legalities: "Legalidades de Formato",
    errorEmptyFilters: "Por favor, introduce algún filtro para buscar.",
    errorEmpty: "El multiverso está vacío. No se encontraron cartas con esta combinación de filtros.",
    decksNav: "Mazos",
    addToDeck: "Añadir al Mazo",
    createDeck: "Crear Mazo",
    newDeckName: "Nombre del mazo...",
    myDecks: "Mis Mazos",
    noDecks: "Aún no tienes ningún mazo.",
    deckCreated: "Mazo creado exitosamente.",
    cardAddedToDeck: "Carta añadida al mazo.",
    deckDeleted: "Mazo eliminado.",
    selectDeck: "Selecciona un Mazo",
    createAndAdd: "Crear y Añadir"
  },
  en: {
    searchParams: "Filters", searchString: "Free Search", searchPlaceholder: "E.g: Proliferate, Dragon...",
    scopeName: "Name", scopeType: "Type", scopeText: "Text",
    uiLang: "UI Language", imgLang: "Art / Image", commander: "Can be Commander",
    colorId: "Color Identity", mainType: "Card Type", rarity: "Rarity", format: "Legal Format",
    creature: "Creature", instant: "Instant", sorcery: "Sorcery", artifact: "Artifact",
    enchantment: "Enchantment", planeswalker: "Planeswalker", anyFormat: "Any",
    cmcMax: 'Max CMC',
    commanderLegal: 'Must be legal as Commander',
    exactMatch: 'Exact Match',
    imageLang: 'Art / Image Language',
    setFilter: 'Set (Edition)',
    searchSet: 'Search set...',
    allSets: 'Any Set',
    common: "Common", uncommon: "Uncommon", rare: "Rare", mythic: "Mythic",
    invoke: "Summon Card", searchCards: "Search Cards",
    welcomeTitle: "Welcome to SeaCards", welcomeDesc: 'Configure your filters in the side panel and press the button to explore the multiverse.',
    scrying: "Scrying the multiverse...", errorEmpty: "The multiverse is empty. Try other filters.",
    otherVersions: "Alternative Styles & Versions",
    savedCards: "SAVED CARDS",
    backToSeaCards: "Back to SeaCards",
    fetchingSaved: "Summoning data from the multiverse...",
    noSavedCards: "Your collection is empty",
    noSavedDesc: "Go back to SeaCards and summon some cards to save them here.",
    noMatchSaved: "No cards match the filters",
    noMatchDesc: "Try clearing the filters in the side panel.",
    saveBtn: "Save to Favorites",
    savingBtn: "Saving...",
    savedAlert: "Saved to Favorites!",
    deleteBtn: "Delete",
    confirmDelete: "Are you sure you want to remove this card from your favorites?",
    searchTitle: "Advanced Search",
    searchDesc: 'Configure your filters and press "Search Cards" to see all possible results.',
    foundCards: "Found",
    cardsMax: "cards (showing max 175)",
    invokeBtn: "Summon",
    searchNav: "Search",
    savedNav: "Favorites",
    logoutTitle: "Logout",
    loginTitle: "Identify yourself to access the Multiverse",
    emailPlaceholder: "you@email.com",
    passwordPlaceholder: "Your password",
    loginBtn: "Enter the Multiverse",
    loggingIn: "Entering...",
    noAccount: "Don't have an account yet?",
    createAccount: "Register here",
    hasAccount: "Already have the keys?",
    loginHere: "Login here",
    marketUsd: "Market (USD)",
    marketEur: "Market (EUR)",
    set: "Set",
    noImage: "No image available",
    manaCmc: "Mana (CMC)",
    min: "Min",
    max: "Max",
    reset: "Reset",
    processing: "Processing...",
    view: "View",
    bannedIn: "Banned in",
    legalities: "Format Legalities",
    errorEmptyFilters: "Please, enter some filters to search.",
    errorEmpty: "The multiverse is empty. No cards found with this combination of filters.",
    decksNav: "Decks",
    addToDeck: "Add to Deck",
    createDeck: "Create Deck",
    newDeckName: "Deck name...",
    myDecks: "My Decks",
    noDecks: "You don't have any decks yet.",
    deckCreated: "Deck created successfully.",
    cardAddedToDeck: "Card added to deck.",
    deckDeleted: "Deck deleted.",
    selectDeck: "Select a Deck",
    createAndAdd: "Create & Add"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('seacards-lang') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('seacards-lang', lang);
  }, [lang]);

  const t = (key) => {
    return TRANSLATIONS[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
